### ISSUE TITLE
Error when using, nothing pops up

### ISSUE THREAD

**Issue by Twizzledrizzle** [eivind88/xkcd#3]
I get the following error in the console (running the latest dev build of Sublime)

``` python
Traceback (most recent call last):
  File "C:\Sublime Text 3 dev\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "xkcd in C:\Sublime Text 3 dev\Data\Installed Packages\Xkcd.sublime-package", line 92, in run
  File "xkcd in C:\Sublime Text 3 dev\Data\Installed Packages\Xkcd.sublime-package", line 98, in getComic
TypeError: 'NoneType' object is not subscriptable
```

And when showing a list:

``` python
Traceback (most recent call last):
  File "C:\Sublime Text 3 dev\sublime_plugin.py", line 535, in run_
    return self.run()
  File "xkcd in C:\Sublime Text 3 dev\Data\Installed Packages\Xkcd.sublime-package", line 162, in run
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1268, in http_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

**Comment by EivindArvesen** [comment]
I've modified the package to give more informative error messages in these cases (update likely pushed within a week), but these errors should only occur if there's a problem with your network or with the xkcd servers.

Is this problem still occurring for you?

**Comment by Twizzledrizzle** [comment]
I am behind a https proxy, but that is configured in user settings - so I guess that should not be a problem?

Error for latest is:

``` python
Traceback (most recent call last):
  File "C:\Sublime Text 3 dev\sublime_plugin.py", line 533, in run_
    return self.run(**args)
  File "xkcd in C:\Sublime Text 3 dev\Data\Installed Packages\Xkcd.sublime-package", line 92, in run
  File "xkcd in C:\Sublime Text 3 dev\Data\Installed Packages\Xkcd.sublime-package", line 98, in getComic
TypeError: 'NoneType' object is not subscriptable
```

**Comment by EivindArvesen** [comment]
It sounds to me as though the proxy-situation may be causing an issue here.
The changes I've talked about haven't been pushed to users yet, but the error you're getting basically means that it isn't getting a (readable) response from the xkcd API.

Try opening [this link](http://xkcd.com/info.0.json) in your browser, and see if you get something like this
![skjermbilde 2015-09-14 kl 15 42 15](https://cloud.githubusercontent.com/assets/939844/9851080/3e8651c4-5af7-11e5-9185-c7382096bf14.png)

**Comment by Twizzledrizzle** [comment]
When using a browser which is configured to use the proxy, I get the following:

``` python
{"month": "9", "num": 1577, "link": "", "year": "2015", "news": "", "safe_title": "Advent", "transcript": "", "alt": "The few dozen doors that have little Christmas trees on them are a nice touch.", "img": "http:\/\/imgs.xkcd.com\/comics\/advent.png", "title": "Advent", "day": "14"}
```

**Comment by Twizzledrizzle** [comment]
I see you use a mac, I have windows, can that be the problem? This plugin looks really nice so it would be great to get it working :)

**Comment by EivindArvesen** [comment]
Thanks!
I'll need to take a more thorough look at how to solve this.

I don't think the platform is a problem, but that the proxy isn't used in the package's requests.

I haven't used Windows in a while – When you say that your proxy is "configured in user settings", does this mean on a system level?
And does it use authentication (e.g. username and password)?

**Comment by Twizzledrizzle** [comment]
I have it in the usersettings in sublime, like so:
`"https_proxy": "proxy.####.####.##:8080"`

without it I cannot download packages from package control, with it package control works fine

**Comment by EivindArvesen** [comment]
Ah, ok.
I'll take a look at the source code of package control (where this variable comes from).
Should be a relatively easy fix.

**Comment by EivindArvesen** [comment]
I think I have just about solved the issue now, but I'd like to be certain before I push an update via Package Control.

If I were to push a dev-branch to Github, would you be able to check it out from the repo and test it?
Also – just to be sure – you're storing your proxy settings in `Package Control.sublime-settings`, right?

**Comment by EivindArvesen** [comment]
@Twizzledrizzle : I have now pushed an update via Package Control.

Please let me know if this solves your problem!

**Comment by Twizzledrizzle** [comment]
Sorry I forgot to reply!

The proxy settings is in the default sublime user setting, not the package control setting

I get the following error now:

Package Control: Upgraded Xkcd to 0.2.1
ignored packages updated to: ["Markdown", "Vintage"]
reloading plugin Xkcd.xkcd
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
error: Xkcd: Xkcd.xkcd: URL error [Errno 11004] getaddrinfo failed contacting API
error: Xkcd: Error reading API response

**Comment by Twizzledrizzle** [comment]
note: adding the proxy settings in package control user settings gives the same error

by the way, thank you for putting time on this, your plugin is awesome from home :)

**Comment by EivindArvesen** [comment]
No problem, and glad to hear it:)

Does the console output your proxy properly though?
Somehing like `Proxies: {'https': 'IP:PORT'}`?

**Comment by EivindArvesen** [comment]
Nevermind, I just figured out a solution.
Have you set a `"http_proxy"` for Sublime Text?
Regardless, how does plain http-requests work for you (if you know of and use any package that perform these)?

Depending on how things work out, you might have to set `"http_proxy"` as well.
According to the [Package Control Docs](https://packagecontrol.io/docs/settings) these should be set in `Preferences > Package Settings > Package Control > Settings – Default`, so this is likely where I'll have the package look for these.

**Comment by EivindArvesen** [comment]
@Twizzledrizzle : I've updated the package; it should finally (hopefully) work for you if you set `"http_proxy"` (same value as https_proxy) in the fashion outlined in my previous comment.

**Comment by Twizzledrizzle** [comment]
Works! Added the HTTP instead of HTTPS, thank you!

—
Niklas

**Comment by EivindArvesen** [comment]
You should probably keep `https_proxy`, as package control may be dependent on this.
Anyway: Great!
Closing the issue.
